require('bokiledobri/basic')
require('bokiledobri/plugs')
require('bokiledobri/mappings')
require('bokiledobri/lspconfig')
require('bokiledobri/cmp')
require('bokiledobri/treesitter')
require('bokiledobri/colorscheme')
